function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy as a
%       percentage. In the app, the Models pane displays this overall
%       accuracy score for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 27-Feb-2023 17:18:40


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'duration', 'amplitude', 'lowpass min', 'lowpass mean Channel spread', 'lowpass maxSlope', 'lowpass minSlope', 'bandpass maxSlope', 'bandpass meanFreq', 'bandpass centerFreq', 'bandpass p2p', 'envelope PCA_1', 'envelope PCA_2', 'envelope PCA_3', 'envelope PCA_4', 'envelope PCA_5', 'lowpass PCA_1', 'lowpass PCA_2', 'lowpass PCA_3', 'lowpass PCA_4', 'lowpass PCA_5', 'lowpass PCA_6', 'lowpass PCA_7', 'lowpass PCA_8', 'lowpass PCA_9', 'lowpass PCA_10', 'Scalogram PCA_1', 'Scalogram PCA_2', 'Scalogram PCA_3', 'Scalogram PCA_4', 'Scalogram PCA_5', 'Scalogram PCA_6', 'Scalogram PCA_7', 'Scalogram PCA_8', 'Scalogram PCA_9', 'Scalogram PCA_10'};
predictors = inputTable(:, predictorNames);
response = inputTable.class;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.

% Expand the Distribution Names per predictor
% Numerical predictors are assigned either Gaussian or Kernel distribution and categorical predictors are assigned mvmn distribution
% Gaussian is replaced with Normal when passing to the fitcnb function
distributionNames =  repmat({'Kernel'}, 1, length(isCategoricalPredictor));
distributionNames(isCategoricalPredictor) = {'mvmn'};

if any(strcmp(distributionNames,'Kernel'))
    classificationNaiveBayes = fitcnb(...
        predictors, ...
        response, ...
        'Kernel', 'Normal', ...
        'Support', 'Unbounded', ...
        'DistributionNames', distributionNames, ...
        'ClassNames', categorical({'randomRipples'; 'selectedRipples'}));
else
    classificationNaiveBayes = fitcnb(...
        predictors, ...
        response, ...
        'DistributionNames', distributionNames, ...
        'ClassNames', categorical({'randomRipples'; 'selectedRipples'}));
end

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
naiveBayesPredictFcn = @(x) predict(classificationNaiveBayes, x);
trainedClassifier.predictFcn = @(x) naiveBayesPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'Scalogram PCA_1', 'Scalogram PCA_10', 'Scalogram PCA_2', 'Scalogram PCA_3', 'Scalogram PCA_4', 'Scalogram PCA_5', 'Scalogram PCA_6', 'Scalogram PCA_7', 'Scalogram PCA_8', 'Scalogram PCA_9', 'amplitude', 'bandpass centerFreq', 'bandpass maxSlope', 'bandpass meanFreq', 'bandpass p2p', 'duration', 'envelope PCA_1', 'envelope PCA_2', 'envelope PCA_3', 'envelope PCA_4', 'envelope PCA_5', 'lowpass PCA_1', 'lowpass PCA_10', 'lowpass PCA_2', 'lowpass PCA_3', 'lowpass PCA_4', 'lowpass PCA_5', 'lowpass PCA_6', 'lowpass PCA_7', 'lowpass PCA_8', 'lowpass PCA_9', 'lowpass maxSlope', 'lowpass mean Channel spread', 'lowpass min', 'lowpass minSlope'};
trainedClassifier.ClassificationNaiveBayes = classificationNaiveBayes;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2022b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'duration', 'amplitude', 'lowpass min', 'lowpass mean Channel spread', 'lowpass maxSlope', 'lowpass minSlope', 'bandpass maxSlope', 'bandpass meanFreq', 'bandpass centerFreq', 'bandpass p2p', 'envelope PCA_1', 'envelope PCA_2', 'envelope PCA_3', 'envelope PCA_4', 'envelope PCA_5', 'lowpass PCA_1', 'lowpass PCA_2', 'lowpass PCA_3', 'lowpass PCA_4', 'lowpass PCA_5', 'lowpass PCA_6', 'lowpass PCA_7', 'lowpass PCA_8', 'lowpass PCA_9', 'lowpass PCA_10', 'Scalogram PCA_1', 'Scalogram PCA_2', 'Scalogram PCA_3', 'Scalogram PCA_4', 'Scalogram PCA_5', 'Scalogram PCA_6', 'Scalogram PCA_7', 'Scalogram PCA_8', 'Scalogram PCA_9', 'Scalogram PCA_10'};
predictors = inputTable(:, predictorNames);
response = inputTable.class;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Set up holdout validation
cvp = cvpartition(response, 'Holdout', 0.3);
trainingPredictors = predictors(cvp.training, :);
trainingResponse = response(cvp.training, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.

% Expand the Distribution Names per predictor
% Numerical predictors are assigned either Gaussian or Kernel distribution and categorical predictors are assigned mvmn distribution
% Gaussian is replaced with Normal when passing to the fitcnb function
distributionNames =  repmat({'Kernel'}, 1, length(trainingIsCategoricalPredictor));
distributionNames(trainingIsCategoricalPredictor) = {'mvmn'};

if any(strcmp(distributionNames,'Kernel'))
    classificationNaiveBayes = fitcnb(...
        trainingPredictors, ...
        trainingResponse, ...
        'Kernel', 'Normal', ...
        'Support', 'Unbounded', ...
        'DistributionNames', distributionNames, ...
        'ClassNames', categorical({'randomRipples'; 'selectedRipples'}));
else
    classificationNaiveBayes = fitcnb(...
        trainingPredictors, ...
        trainingResponse, ...
        'DistributionNames', distributionNames, ...
        'ClassNames', categorical({'randomRipples'; 'selectedRipples'}));
end

% Create the result struct with predict function
naiveBayesPredictFcn = @(x) predict(classificationNaiveBayes, x);
validationPredictFcn = @(x) naiveBayesPredictFcn(x);

% Add additional fields to the result struct


% Compute validation predictions
validationPredictors = predictors(cvp.test, :);
validationResponse = response(cvp.test, :);
[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);

% Compute validation accuracy
correctPredictions = (validationPredictions == validationResponse);
isMissing = ismissing(validationResponse);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
